version: "3"

services:
  www:
    build: .
    container_name: www
    volumes:
      - "./src:/var/www/html:rw"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  # MySQL database
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employer
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql-data:
